MVCApp/Models/Proizvod.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCApp.Models
{
    public class Proizvod
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Kategorija { get; set; }
        public string Proizvodjac { get; set; }
        public string Dobavljac { get; set; }
        public double Cena { get; set; }
    }
}

MVCApp/Models/Proizvodi.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContextEntities : DbContext
    {
        public DataContextEntities()
            : base("name=DataContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Proizvodi> Proizvodis { get; set; }
    }
}

MVCApp/Models/Proizvodi.Designer.cs
// T4 code generation is enabled for model 'C:\Users\andreja\Desktop\MVCApp\MVCApp\Models\Proizvodi.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

MVCApp/Models/Proizvodi.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodi
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Kategorija { get; set; }
        public string Proizvodjac { get; set; }
        public string Dobavljac { get; set; }
        public double Cena { get; set; }
    }
}

MVCApp/Models/Proizvodi1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

MVCApp/Controllers/HomeController.cs
using MVCApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCApp.Controllers
{

    public class HomeController : Controller
    {
        private DataContextEntities _context = new DataContextEntities();


        // GET: Home
        public ActionResult Index()
        {
            return View(_context.Proizvodis.ToList());
        }

        // GET: Home/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: Home/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Home/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Id")] Proizvodi proizvod)
        {
            if (!ModelState.IsValid)
                return View();

            _context.Proizvodis.Add(proizvod);
            _context.SaveChanges();

            return RedirectToAction("Index");

        }

        // GET: Home/Edit/5
        public ActionResult Edit(int id)
        {
            var proizvodZaIzmenu = _context.Proizvodis.Where(proizvod => proizvod.Id == id).FirstOrDefault();

            return View(proizvodZaIzmenu);
        }

        // POST: Home/Edit/5
        [HttpPost]
        public ActionResult Edit(Proizvodi proizvodZaIzmenu)
        {
            var proizvodIzBaze = _context.Proizvodis.Where(proizvod => proizvod.Id == proizvodZaIzmenu.Id).FirstOrDefault();

            if (!ModelState.IsValid)
                return View(proizvodIzBaze);

            _context.Entry(proizvodIzBaze).CurrentValues.SetValues(proizvodZaIzmenu);
            _context.SaveChanges();

            return RedirectToAction("Index");



        }

    }
}

MVCApp/Controllers/ProizvodController.cs
using MVCApp.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCApp.Controllers
{
    public class ProizvodController : Controller
    {
        public ActionResult Index()
        {
            List<Proizvod> proizvodi = new List<Proizvod>();
            JSONReadWrite readWrite = new JSONReadWrite();
            proizvodi = JsonConvert.DeserializeObject<List<Proizvod>>(readWrite.Read("proizvodi.json", "data"));
            return View("~/Views/Proizvod/View.cshtml", proizvodi);
        }

        [HttpPost]
        public ActionResult Index(Proizvod proizvodi)
        {
            List<Proizvod> listaProzivoda = new List<Proizvod>();
            JSONReadWrite readWrite = new JSONReadWrite();
            listaProzivoda = JsonConvert.DeserializeObject<List<Proizvod>>(readWrite.Read("proizvodi.json", "data"));

            Proizvod proizvod = listaProzivoda.FirstOrDefault(x => x.Id == proizvodi.Id);

            if (proizvod == null)
            {
                listaProzivoda.Add(proizvodi);
            }
            else
            {
                int index = listaProzivoda.FindIndex(x => x.Id == proizvodi.Id);
                listaProzivoda[index] = proizvodi;
            }

            string jSONString = JsonConvert.SerializeObject(listaProzivoda);
            readWrite.Write(jSONString);

            return View("~/Views/Proizvod/View.cshtml", listaProzivoda);
        }
    }

    public class JSONReadWrite
    {
        public JSONReadWrite() { }

        public string Read(string fileName, string location)
        {
            var path = System.Web.HttpContext.Current.Server.MapPath("data/proizvodi.json");

            string jsonResult;

            using (StreamReader streamReader = new StreamReader(path))
            {
                jsonResult = streamReader.ReadToEnd();
            }
            return jsonResult;
        }

        public void Write(string jSONString)
        {

            var path = System.Web.HttpContext.Current.Server.MapPath("data/proizvodi.json");

            using (var streamWriter = File.CreateText(path))
            {
                streamWriter.Write(jSONString);
            }
        }
    }
}

MVCApp/Views/Home/Create.cshtml
@model MVCApp.Models.Proizvodi

@{
    ViewBag.Title = "Create";
}

<h2>Kreiraj nov proizvod</h2>
<br />


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Proizvod</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kategorija, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kategorija, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kategorija, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Proizvodjac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Proizvodjac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Proizvodjac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dobavljac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dobavljac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dobavljac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kreiraj" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak na listu proizvoda", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCApp/Views/Home/Edit.cshtml
@model MVCApp.Models.Proizvodi

@{
    ViewBag.Title = "Edit";
}

<h2>Izmeni podatke o proizvodu</h2>
<br />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Podaci o proizvodu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kategorija, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kategorija, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kategorija, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Proizvodjac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Proizvodjac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Proizvodjac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dobavljac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dobavljac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dobavljac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sacuvaj izmene" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak na listu proizvoda", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCApp/Views/Home/Index.cshtml
@model IEnumerable<MVCApp.Models.Proizvodi>

@{
    ViewBag.Title = "Index";
}

<h2>Dostupni proizvodi iz baze</h2>
<br />

<p>
    @Html.ActionLink("Kreiraj nov proizvod", "Create")
</p>
<p>
    @Html.ActionLink("Pregled proizvoda iz JSON fajla", "Index", "Proizvod")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kategorija)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Proizvodjac)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dobavljac)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cena)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Opis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kategorija)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Proizvodjac)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dobavljac)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cena)
        </td>
        <td>
            @Html.ActionLink("Izmeni", "Edit", new { id=item.Id })
        </td>
    </tr>
}

</table>

MVCApp/Views/Proizvod/View.cshtml
@model List<MVCApp.Models.Proizvod>

@{
    ViewBag.Title = "View";
}


<h2>Pregled svih proizvoda iz JSON fajla</h2>
<br />
@foreach (var item in Model)
{
    <p>
        Id: @item.Id<br />
        Naziv: @item.Naziv<br />
        Opis: @item.Opis<br />
        Kategorija: @item.Kategorija<br />
        Proizvodjac: @item.Proizvodjac<br />
        Dobavljac: @item.Dobavljac<br />
        Cena: @item.Cena<br />
    </p>

}


<h2>Dodaj ili izmeni proizvod</h2>
<h4>Za izmenu podataka o proizvodu uneti njegov id</h4>
<br />
@using (Html.BeginForm("Index", "Proizvod", FormMethod.Post))
{
    MVCApp.Models.Proizvod proizvod = new MVCApp.Models.Proizvod();
    <label asp-for="@proizvod.Id">Id</label>
    <br />
    <input type="text" asp-for="@proizvod.Id" name="Id" />
    <br />
    <br />
    <label asp-for="@proizvod.Naziv">Naziv</label>
    <br />
    <input type="text" asp-for="@proizvod.Naziv" name="Naziv" />
    <br />
    <br />
    <label asp-for="@proizvod.Opis">Opis</label>
    <br />
    <input type="text" asp-for="@proizvod.Opis" name="Opis" />
    <br />
    <br />
    <label asp-for="@proizvod.Kategorija">Kategorija</label>
    <br />
    <input type="text" asp-for="@proizvod.Kategorija" name="Kategorija" />
    <br />
    <br />
    <label asp-for="@proizvod.Proizvodjac">Proizvodjac</label>
    <br />
    <input type="text" asp-for="@proizvod.Proizvodjac" name="Proizvodjac" />
    <br />
    <br />
    <label asp-for="@proizvod.Dobavljac">Dobavljac</label>
    <br />
    <input type="text" asp-for="@proizvod.Dobavljac" name="Dobavljac" />
    <br />
    <br />
    <label asp-for="@proizvod.Cena">Cena</label>
    <br />
    <input type="text" asp-for="@proizvod.Cena" name="Cena" />
    <br />
    <br />

    <input type="submit" value="Kreiraj ili izmeni" class="btn btn-success"/>
}

MVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MVCApp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVCApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>MVCApp</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>